console.log("hii");

try{
console.log("inside try block start");
console.log("inside try block start");

// throw new Error("something went wrong");
console.log("inside try block end");
}catch(error){
console.log("inside catch");
}